# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendar_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calendar_tab(object):
    def setupUi(self, calendar_tab):
        calendar_tab.setObjectName("calendar_tab")
        calendar_tab.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(calendar_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calendar_widget = QtWidgets.QCalendarWidget(calendar_tab)
        self.calendar_widget.setObjectName("calendar_widget")
        self.horizontalLayout.addWidget(self.calendar_widget)

        self.retranslateUi(calendar_tab)
        QtCore.QMetaObject.connectSlotsByName(calendar_tab)

    def retranslateUi(self, calendar_tab):
        _translate = QtCore.QCoreApplication.translate
        calendar_tab.setWindowTitle(_translate("calendar_tab", "Calendar Tab"))
