# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1073, 597)
        self.horizontalLayout = QtWidgets.QHBoxLayout(main_window)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pages_tab_widget = QtWidgets.QTabWidget(main_window)
        self.pages_tab_widget.setObjectName("pages_tab_widget")
        self.horizontalLayout_2.addWidget(self.pages_tab_widget)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(main_window)
        self.pages_tab_widget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Nudgy"))
