# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/screen_time_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_time_tab(object):
    def setupUi(self, screen_time_tab):
        screen_time_tab.setObjectName("screen_time_tab")
        screen_time_tab.resize(450, 307)
        self.horizontalLayout = QtWidgets.QHBoxLayout(screen_time_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.screen_time_table_widget = QtWidgets.QTableWidget(screen_time_tab)
        self.screen_time_table_widget.setObjectName("screen_time_table_widget")
        self.screen_time_table_widget.setColumnCount(4)
        self.screen_time_table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.screen_time_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.screen_time_table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.screen_time_table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.screen_time_table_widget.setHorizontalHeaderItem(3, item)
        self.screen_time_table_widget.horizontalHeader().setCascadingSectionResizes(False)
        self.screen_time_table_widget.horizontalHeader().setStretchLastSection(True)
        self.screen_time_table_widget.verticalHeader().setSortIndicatorShown(False)
        self.screen_time_table_widget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.screen_time_table_widget)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.update_screen_time_button = QtWidgets.QCheckBox(screen_time_tab)
        self.update_screen_time_button.setObjectName("update_screen_time_button")
        self.horizontalLayout_9.addWidget(self.update_screen_time_button)
        self.label = QtWidgets.QLabel(screen_time_tab)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.screen_time_history = QtWidgets.QLineEdit(screen_time_tab)
        self.screen_time_history.setObjectName("screen_time_history")
        self.horizontalLayout_9.addWidget(self.screen_time_history, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(screen_time_tab)
        QtCore.QMetaObject.connectSlotsByName(screen_time_tab)

    def retranslateUi(self, screen_time_tab):
        _translate = QtCore.QCoreApplication.translate
        screen_time_tab.setWindowTitle(_translate("screen_time_tab", "Screen Time Tab"))
        self.screen_time_table_widget.setSortingEnabled(True)
        item = self.screen_time_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("screen_time_tab", "Application (name)"))
        item = self.screen_time_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("screen_time_tab", "Application (path)"))
        item = self.screen_time_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("screen_time_tab", "Time (hours)"))
        item = self.screen_time_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("screen_time_tab", "Usage (percent)"))
        self.update_screen_time_button.setText(_translate("screen_time_tab", "Scan applications"))
        self.label.setText(_translate("screen_time_tab", "History (hours)"))
