# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\timer_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimerWindow(object):
    def setupUi(self, TimerWindow):
        TimerWindow.setObjectName("TimerWindow")
        TimerWindow.resize(536, 462)
        self.verticalLayout = QtWidgets.QVBoxLayout(TimerWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timer_label = QtWidgets.QLabel(TimerWindow)
        font = QtGui.QFont()
        font.setPointSize(75)
        self.timer_label.setFont(font)
        self.timer_label.setText("")
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.verticalLayout.addWidget(self.timer_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_stop_button = QtWidgets.QPushButton(TimerWindow)
        self.start_stop_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.start_stop_button.setFont(font)
        self.start_stop_button.setObjectName("start_stop_button")
        self.horizontalLayout.addWidget(self.start_stop_button)
        self.pause_resume_button = QtWidgets.QPushButton(TimerWindow)
        self.pause_resume_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pause_resume_button.setFont(font)
        self.pause_resume_button.setObjectName("pause_resume_button")
        self.horizontalLayout.addWidget(self.pause_resume_button)
        self.start_time_line_edit = QtWidgets.QLineEdit(TimerWindow)
        self.start_time_line_edit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.start_time_line_edit.setFont(font)
        self.start_time_line_edit.setText("")
        self.start_time_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.start_time_line_edit.setObjectName("start_time_line_edit")
        self.horizontalLayout.addWidget(self.start_time_line_edit)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(TimerWindow)
        QtCore.QMetaObject.connectSlotsByName(TimerWindow)

    def retranslateUi(self, TimerWindow):
        _translate = QtCore.QCoreApplication.translate
        TimerWindow.setWindowTitle(_translate("TimerWindow", "Form"))
        self.start_stop_button.setText(_translate("TimerWindow", "Start"))
        self.pause_resume_button.setText(_translate("TimerWindow", "Pause"))
