# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\timer_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_timer_tab(object):
    def setupUi(self, timer_tab):
        timer_tab.setObjectName("timer_tab")
        timer_tab.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(timer_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timer_label = QtWidgets.QLabel(timer_tab)
        font = QtGui.QFont()
        font.setPointSize(75)
        self.timer_label.setFont(font)
        self.timer_label.setText("")
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.verticalLayout.addWidget(self.timer_label)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.start_stop_button = QtWidgets.QPushButton(timer_tab)
        self.start_stop_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.start_stop_button.setFont(font)
        self.start_stop_button.setObjectName("start_stop_button")
        self.horizontalLayout_7.addWidget(self.start_stop_button)
        self.pause_resume_button = QtWidgets.QPushButton(timer_tab)
        self.pause_resume_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pause_resume_button.setFont(font)
        self.pause_resume_button.setObjectName("pause_resume_button")
        self.horizontalLayout_7.addWidget(self.pause_resume_button)
        self.start_time_line_edit = QtWidgets.QLineEdit(timer_tab)
        self.start_time_line_edit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.start_time_line_edit.setFont(font)
        self.start_time_line_edit.setText("")
        self.start_time_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.start_time_line_edit.setObjectName("start_time_line_edit")
        self.horizontalLayout_7.addWidget(self.start_time_line_edit)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(timer_tab)
        QtCore.QMetaObject.connectSlotsByName(timer_tab)

    def retranslateUi(self, timer_tab):
        _translate = QtCore.QCoreApplication.translate
        timer_tab.setWindowTitle(_translate("timer_tab", "Timer Tab"))
        self.start_stop_button.setText(_translate("timer_tab", "Start"))
        self.pause_resume_button.setText(_translate("timer_tab", "Pause"))
