# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\to_do_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_to_do_tab(object):
    def setupUi(self, to_do_tab):
        to_do_tab.setObjectName("to_do_tab")
        to_do_tab.resize(514, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(to_do_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(to_do_tab)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(to_do_tab)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.task_description_line_edit = QtWidgets.QLineEdit(to_do_tab)
        self.task_description_line_edit.setObjectName("task_description_line_edit")
        self.horizontalLayout_4.addWidget(self.task_description_line_edit)
        self.label_2 = QtWidgets.QLabel(to_do_tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.due_date_time_edit = QtWidgets.QDateTimeEdit(to_do_tab)
        self.due_date_time_edit.setObjectName("due_date_time_edit")
        self.horizontalLayout_4.addWidget(self.due_date_time_edit)
        self.add_task_button = QtWidgets.QPushButton(to_do_tab, clicked=lambda: addItem(self))
        self.add_task_button.setObjectName("add_task_button")
        self.horizontalLayout_4.addWidget(self.add_task_button)
        self.remove_task_button = QtWidgets.QPushButton(to_do_tab, clicked=lambda: deleteItem(self))
        self.remove_task_button.setObjectName("remove_task_button")
        self.horizontalLayout_4.addWidget(self.remove_task_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)

        def addItem(self):
            item = self.task_description_line_edit.text() + ' Due: ' + self.due_date_time_edit.text()
            self.listWidget.addItem(item)

        def deleteItem(self):
            clicked = self.listWidget.currentRow()
            self.listWidget.takeItem(clicked)


        self.retranslateUi(to_do_tab)
        QtCore.QMetaObject.connectSlotsByName(to_do_tab)

    def retranslateUi(self, to_do_tab):
        _translate = QtCore.QCoreApplication.translate
        to_do_tab.setWindowTitle(_translate("to_do_tab", "To-Do Tab"))
        self.label.setText(_translate("to_do_tab", "Task:"))
        self.label_2.setText(_translate("to_do_tab", "Due Date (Optional): "))
        self.add_task_button.setText(_translate("to_do_tab", "Add"))
        self.remove_task_button.setText(_translate("to_do_tab", "Remove"))
