name: CI

on:
  push:
    # branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      QT_QPA_PLATFORM: offscreen
      XDG_RUNTIME_DIR: /tmp
      XDG_DATA_DIRS: /usr/share
      PYTHONWARNINGS: ignore::DeprecationWarning

    permissions:
      pages: write
      id-token: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpulse-mainloop-glib0 \
            libpulse0 \
            pulseaudio \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-libav

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest -q \
            --cov=. \
            --cov-report=term \
            --cov-report=xml \
            --cov-report=html \

      - name: Prepare the webpage
        run: |
          mkdir sites
          mv htmlcov sites/
          mv coverage.xml sites/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./htmlcov

      - name: deploy the artifacts
        uses: actions/deploy-pages@v4