name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    # permissions:
    #   pages: write
    #   id-token: write
    #   actions: read

    env:
      QT_QPA_PLATFORM: offscreen
      XDG_RUNTIME_DIR: /tmp
      XDG_DATA_DIRS: /usr/share
      PYTHONWARNINGS: ignore::DeprecationWarning

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpulse-mainloop-glib0 \
            libpulse0 \
            pulseaudio \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-libav

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # - name: Run basic tests
      #   run: pytest -q

      - name: Run tests with coverage
        run: |
          pytest -q \
            --cov=. \
            --cov-report=term \
            --cov-report=xml \
            --cov-report=html \

      - name: Prepare the webpage
        run: |
          mkdir sites
          mv htmlcov sites/
          mv coverage.xml sites/

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: ./sites/